.PHONY: build-tailwind
build-tailwind:
	npx tailwindcss -i tailwind/main.css -o resources/public/compiled/main.css

.PHONY: watch-tailwind
watch-tailwind:
	npx tailwindcss -i tailwind/main.css -o resources/public/compiled/main.css --watch
